### ISSUE TITLE
wifi will not work with AsyncWebServer_WT32_ETH01

### ISSUE THREAD

**Issue by SurfGargano** [khoih-prog/AsyncWebServer_WT32_ETH01#1]
Thank you for the lib AsyncWebServer_WT32_ETH01.
I have a problem to connect the WT32 to wifi, always failed in connection.

    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, password);
    if (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.printf("WiFi Failed!\n");
        return;
    }

can you please give me an example, so that I can test it.

 I have set the board = esp32doit-devkit-v1 as you suggested.
but the compiler send a warning : 
In file included from src\main.cpp:32:0:
.pio\libdeps\esp32dev\WebServer_WT32_ETH01\src/WebServer_WT32_ETH01.h:43:6: warning: #warning Using code for ESP32 core v1.0.6- in WebServer_WT32_ETH01.h [-Wcpp]
     #warning Using code for ESP32 core v1.0.6- in WebServer_WT32_ETH01.h
      ^
.pio\libdeps\esp32dev\WebServer_WT32_ETH01\src/WebServer_WT32_ETH01.h:50:4: warning: #warning Using ESP32 architecture for WebServer_WT32_ETH01 [-Wcpp]
   #warning Using ESP32 architecture for WebServer_WT32_ETH01

What goes wrong ?

**Comment by khoih-prog** [comment]
You can ignore these `warnings` as they are not error messages.

> #warning Using code for ESP32 core **v1.0.6-** in WebServer_WT32_ETH01.h

Anyway, you also have to read the warnings and know that you are still using the out-of-date ESP32 core version. Please update to the latest core v2.0.1.

If you're not familiar with programming / complex configuration, please use Arduino IDE to verify if your code is working first, before moving to `more demanding PIO`.

The not-connecting WiFi debug is the most basic step in debugging, and I expect you will find out the reason yourself as I won't spend time here. Also this library is designed for **WT32_ETH01 board to use Ethernet, not WiFi**, and have nothing to do with your WiFi connection at all.

Post your request for help in  Arduino or ESP32 Forum.

Good Luck,
